// Generated by CoffeeScript 1.11.0
(function($) {

  /*
  	$(document).ready ->
  		owlCarusel = $('ul#pptx-line')
  		owlCarusel.owlCarousel({
  			loop: false
  			margin: 10
  			items: 5
  			
  			})
   */
  return Drupal.behaviors.PptOwlCarusel = {
    attach: function(context, settings) {
      return $(document).ready(function() {
        var owlCarusel;
        owlCarusel = $('ul#pptx-line');
        return owlCarusel.owlCarousel({
          loop: false,
          margin: 10,
          items: settings.KrausPpt.owlCount,
          lazyLoad: true,
          nav: true,
          navText: ['', '']
        });
      });
    }
  };
})(jQuery);
